seeds:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9

dataset_kwargs:
  n_samples: 800
  n_features: 3
  n_classes: 3
  n_labels: 2
  length: 500
  allow_unlabeled: true
  sparse: false
  test_size: 0.25
  avg_trace: 0.65

train:
  cv_n_folds: 5
  seed: 0

eval:
  ks:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 10
  - 20
  - 50
  - 100
  temperatures:
  - 0.01
  - 0.1
  - 1
  - 10
  - 100
  alphas:
  - 0.01
  - 0.1
  - 1
  - 10
  - 100
